### ISSUE TITLE
Testing Plan and Results

### ISSUE THREAD

**Issue by kevinlcaiug** [dartmouth-cs98/21f-decentralized-health#110]
# Dogfooding/Testing
 
## Landing Page/Onboarding
1. Open up the webapp- attempt to create a new account
__Q: Should we include a blurb about metamask?
    - Definitely: should tell them how to use it, what it is, why we use it
    - Definitely would be helpful given a lot of people have never used a wallet before.
3. from there login and see the prompt for metamask login. 
__Q: Is the sign-in intuitive and concise. 
    - The sign-in process made sense and we had no problems with it.
__Q: Is the metamask information understandable/ digestable
    - It made sense for those of us who had used metamask before, but was difficult for those who have not seen it.

## Feature 1: Information blocks
1. read the information if you would like 
__Q: How is the wording?
    - Easily understandable
__Q: Is this something you would take the time to read if you navigated to this page?
    - Yes since it's something we're unfamiliar with
__Q: Is the text conveniently placed/ easily digestible.
    - Yes

2. continue with the tutorial 

    We were not exactly sure what you meant by the tutorial. Is this something you are planning on adding in the future?
    
__Q: Are the tutorial slides hindering your ability to freely explore the website 
__Q: Are you able to follow the steps?
__Q: Do you feel like these are restrictive, or you'd prefer them to be optional?
--Q: Do you find it answering questions you have about the blockchain or what it means to store data on the blockchain?

## Feature 2: Sign in page 
1. Fill in sign up info, login into metamask 
 
__Q: Is the information that is displayed relevant and concise?
    - Yes especially if you are less familiar with Web3.0 technologies
__Q: Do you understand why we require both typical login info (email, password) and metamask to log in?
    - Yes, we got that there was both a centralized and decentralized aspect to the project
    - Do you care?
        - Would there be a way to do it completely decentralized

## Feature 3: Files
1. Uploading Files on Doctor Side

__Q: Does this usage seem intuitive enough?
Yes
__Q: Are there other types of files you foresee us needing?
    - Not too sure as we don't know too much about the medical record system
__Q: Do you understand the flow for how to add files for a specific patient?
    - Note: definitely need to add ability to search for a patient
    - Yes it was quite intuitive
__Q: Should we allow the doctor to type in the desired file name, or just take the name of the .txt file?
    - Should not matter too much. The doctor can always rename it on their computer.

2. Viewing Files on either the doctor or patient side
__Q: Does the file system seem empty?
    - Seemed fine to us
__Q: What other info for the files do you think would be valuable to store?
    - Maybe the last time the file was accessed

3. Search/Sort Files
__Q:  Do you see the use cases of this?
    - Not sure how many files the typical person has, but if it is a lot then yes
__Q:  Does any of the setup not make sense? Do we need to more explicitly show that our button helps sort files?
    - We were able to tell

## Feature 4: admin view vs patient view 
1. login as both, go to name and click the other persons view 
__Q: Does it need to be more clear to the user that they are looking at the admin/patients view?
    - We don't think so
__Q: Was it obvious that it is possible to change the view, and was it easy to find the button?
    - Yes, quite intuitive

## Feature 5: revoke access 
1. login as both, go to name and click the other persons view 
__Q:  Did the user flow make sense to you?
    - Yes very simple
__Q:  Was the placement of the button intuitive for user experience?
    - Yes
    

# Feedback and Suggestions
1. Handling error/empty states on dashboard
- e.g. when there are no files in patient records, when blockchain transactions fail
2. Landing page UI polish
3. Blockchain FAQs/support page?

# Bug Reports
_please list any bug reports and attach screenshots here_
* Signing In existing user

**Comment by timofei7** [comment]
@testing team - have you finished with this?  looks like some questions weren't answered?  if there are bugs feel free to screenshot them.
