### ISSUE TITLE
Sprint Retrospective - Term 2 Week 7

### ISSUE THREAD

**Issue by kevinlcaiug** [dartmouth-cs98/21f-decentralized-health#112]
## Sprint #7 Retrospective:
* members in attendance:
  ![selfie proof of meeting]()
  - [x] Gabe
  - [x] Kevin
  - [x] Chibuzo
  - [ ] Scott
  - [x] Elorm
  - [x] Tanvir
* what worked well
  * Blockchain:
    * Added date_uploaded variable to file struct
    * Tested and validated its proper usage and functionality
  * Frontend:
    * Completed feature to toggle between admin and patient view
    * Completed file search and sort feature
    * UI Polish on admin and patient dashboards and file tables
    * Began implementation of tutorial - switched from using Shepherd to React joyride and ironing out bugs before full implementation
    * Experimenting with adding animations whenever a smart contract executes 
    * Considering and experimenting with potential UI updates for the sidebar navigation
  * Backend:
      * Identified issue with signing up - we are currently only signing up users as either an admin or patient. Our shift to an educational app removes the necessity.
* what didn't
    * We had some problems with coding the tutorial/tour for the front-end causing us to switch frameworks which was time consuming to read documentation for both

* self assessment on progress
     *give an estimate of how far towards your goals you are, do you think you're on track?* *lay out *each* of the following weeks till end of term with brief goals for each*
  * Blockchain: fully done, awaiting further integration with frontend
      * Getting contact info of admin/patient in solidity contract
  * Backend: Fully integrated and complete
          * small changes may be made along the way for UX purposes
  * Frontend: on track to final form. Most decisions now are design ones.
      * current week: .
          * SignUp as both patient, admin
          * More polish, and testing
          * Tutorial, Privacy/FAQ page
          * Refactoring commonalities between patient and admin 
      * week #8: CSS jazz, particularly for the landing page and experimenting with adding some colour to other pages of the app.
      * week #9: Bug hunting, UI and UX tweaking, final contract redeployment
* briefly summarize any other topics/discussions

**Comment by timofei7** [comment]
send a link to hosted beta version anytime!

**Comment by timofei7** [comment]
and screenshots or it didn't happen
